import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, ChevronRight } from "lucide-react";
import { notFound } from "next/navigation";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { ArticleInteractions } from "@/components/article-interactions";
import { LiveTravelWidgets } from "@/components/live-travel-widgets";
import { database } from "@/lib/database";
import { sanitizeArticleHtml } from "@/lib/content-admin";
import { canonicalArticleHref } from "@/lib/content-routes";

type Row={title:string;slug:string;category:string|null;summary:string|null;image:string|null;payload:string;updated_at:string};
type CmsMap={name?:string;address?:string;embedUrl?:string};
const categories:Record<string,{region:string;label:string;href:string}>={
  accommodation:{region:"호치민",label:"숙소 & 풀빌라",href:"/ho-chi-minh/accommodation"},karaoke:{region:"호치민",label:"가라오케",href:"/ho-chi-minh/karaoke"},club:{region:"호치민",label:"클럽",href:"/ho-chi-minh/club"},bar:{region:"호치민",label:"바 & 주점",href:"/ho-chi-minh/bar"},salon:{region:"호치민",label:"이발소 & 미용실",href:"/ho-chi-minh/salon"},massage:{region:"호치민",label:"마사지",href:"/ho-chi-minh/massage"},golf:{region:"호치민",label:"골프",href:"/ho-chi-minh/golf"},sights:{region:"호치민",label:"여행지",href:"/ho-chi-minh/travel"},restaurant:{region:"호치민",label:"맛집",href:"/ho-chi-minh/restaurant"},
  danangroom:{region:"다낭",label:"숙소 & 풀빌라",href:"/da-nang/accommodation"},danangkaraoke:{region:"다낭",label:"가라오케",href:"/da-nang/karaoke"},danangclub:{region:"다낭",label:"클럽",href:"/da-nang/club"},danangbar:{region:"다낭",label:"바 & 주점",href:"/da-nang/bar"},danangsalon:{region:"다낭",label:"이발소 & 미용실",href:"/da-nang/salon"},danangmassage:{region:"다낭",label:"마사지",href:"/da-nang/massage"},danangfood:{region:"다낭",label:"맛집",href:"/da-nang/restaurant"},
  nhatrangktv:{region:"나트랑",label:"가라오케",href:"/nha-trang/karaoke"},nhatrangclub:{region:"나트랑",label:"클럽",href:"/nha-trang/club"},nhatrangsalon:{region:"나트랑",label:"이발소 & 미용실",href:"/nha-trang/salon"},nhatrangmassage:{region:"나트랑",label:"마사지",href:"/nha-trang/massage"},dalatktv:{region:"달랏",label:"가라오케",href:"/da-lat/karaoke"},vungtau:{region:"붕따우",label:"붕따우",href:"/vung-tau"},phuquoc:{region:"푸꾸옥",label:"푸꾸옥",href:"/phu-quoc"},
};
const archiveBanners:Record<string,[string,string]>={
  accommodation:["/vietdalbam/upload/48e5ebc917c04ffc91d4f6cfbcc4004b.webp","/vietdalbam/upload/5b3aadbfaeb644499e9070de0daf54d4.webp"],karaoke:["/vietdalbam/upload/karaoke-korean-banner.webp","/vietdalbam/upload/karaoke-local-banner.webp"],salon:["/vietdalbam/upload/salon-banner-1.webp","/vietdalbam/upload/salon-banner-2.webp"],massage:["/vietdalbam/upload/massage-banner-1.webp","/vietdalbam/upload/massage-banner-2.webp"],restaurant:["/vietdalbam/upload/restaurant-banner-1.webp","/vietdalbam/upload/restaurant-banner-2.webp"],danangroom:["/vietdalbam/upload/48e5ebc917c04ffc91d4f6cfbcc4004b.webp","/vietdalbam/upload/5b3aadbfaeb644499e9070de0daf54d4.webp"],danangkaraoke:["/vietdalbam/upload/karaoke-korean-banner.webp","/vietdalbam/upload/karaoke-local-banner.webp"],danangsalon:["/vietdalbam/upload/salon-banner-1.webp","/vietdalbam/upload/salon-banner-2.webp"],danangmassage:["/vietdalbam/upload/massage-banner-1.webp","/vietdalbam/upload/massage-banner-2.webp"],danangfood:["/vietdalbam/upload/restaurant-banner-1.webp","/vietdalbam/upload/restaurant-banner-2.webp"],
};
const archiveFilters:Record<string,string[]>={accommodation:["전체","아파트","풀빌라","호텔"],danangroom:["전체","풀빌라","3룸","4룸","5룸"],karaoke:["전체","한인","로컬"],danangkaraoke:["전체","한인","로컬"],club:["전체","클럽","라운지"],danangclub:["전체","클럽","라운지"],bar:["전체","토킹바","라운지","펍"],danangbar:["전체","토킹바","라운지","펍"],salon:["전체","이발소","미용실"],danangsalon:["전체","이발소","스파","네일"],massage:["전체","마사지","스파"],danangmassage:["전체","마사지","스파","로컬"],restaurant:["전체","한식","로컬"],danangfood:["전체","BBQ","로컬","한식"]};
function find(slug:string){return database.prepare("SELECT title,slug,category,summary,image,payload,updated_at FROM content_items WHERE kind='cms_article' AND slug=? AND status='published'").get(decodeURIComponent(slug)) as Row|undefined}
type Related={title:string;slug:string;image:string|null;updated_at:string;href:string|null;kind:string};
function related(category:string|null,slug:string){return database.prepare("SELECT title,slug,image,updated_at,href,kind FROM content_items WHERE kind IN ('article','cms_article') AND status='published' AND category IS ? AND slug!=? ORDER BY CASE kind WHEN 'cms_article' THEN 0 ELSE 1 END, updated_at DESC LIMIT 8").all(category,slug) as Related[]}
function relatedHref(item:Related,category:string|null){return item.kind==="cms_article"?`/article/${item.slug}`:canonicalArticleHref(category??"",item.href??"")}
function relatedImage(image:string|null){if(!image)return null;if(image.startsWith("/uploads/admin/"))return image;const filename=image.match(/\/upload\/([^?]+)/)?.[1];return filename?`/vietdalbam/upload/${filename.replace(/\.webp$/,".thumbnail.webp")}`:image}
function content(row:Row){let body="";let map:CmsMap={};try{const payload=JSON.parse(row.payload) as {body?:string;cmsMap?:CmsMap};body=sanitizeArticleHtml(payload.body??"");map=payload.cmsMap??{}}catch{}if(map.embedUrl&&!/<iframe[^>]+google\./i.test(body)){const name=map.name||"Google Maps";body+=`<div class="article-map-embed"><p class="article-map-note"><strong>${name}</strong><span>${map.address??""}</span></p><div class="article-map-frame"><iframe title="${name} Google Maps" src="${map.embedUrl}" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></div></div>`}return body}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const row=find((await params).slug);return row?{title:`${row.title} | 호치민 게임`,description:row.summary??undefined}:{};}

export default async function ArticlePage({params}:{params:Promise<{slug:string}>}){
  const row=find((await params).slug);if(!row)notFound();const categoryKey=row.category??"";const category=categories[categoryKey]??{region:"호치민 게임",label:"게시물",href:"/"};const recommendations=related(row.category,row.slug);const archiveItems:Related[]=[{title:row.title,slug:row.slug,image:row.image,updated_at:row.updated_at,href:`/article/${row.slug}`,kind:"cms_article"},...recommendations].slice(0,9);const date=new Date(row.updated_at).toLocaleDateString("ko-KR");const banners=archiveBanners[categoryKey];const filters=archiveFilters[categoryKey]??["전체"];
  return <main className="min-h-screen overflow-x-hidden bg-[#f3f1ec]">
    <Header/>
    <section className="w-full max-w-full overflow-hidden px-3 pb-14 pt-24 md:pt-28"><div className="mx-auto w-full max-w-[1280px]">
      <nav className="mb-5 flex flex-wrap items-center gap-2 text-[11px] tracking-[.1em] text-muted-foreground uppercase"><Link href="/">홈</Link><ChevronRight className="h-3 w-3"/><span>{category.region}</span><ChevronRight className="h-3 w-3"/><Link href={category.href}>{category.label}</Link><ChevronRight className="h-3 w-3"/><span className="max-w-[42vw] truncate text-foreground">{row.title}</span></nav>
      <div className="grid min-w-0 max-w-full items-start gap-5 lg:grid-cols-[minmax(0,940px)_320px]">
        <article className="w-full min-w-0 max-w-full overflow-hidden rounded-[12px] bg-card px-5 py-6 shadow-[0_1px_2px_rgba(0,0,0,.04)]">
          <header className="mb-11 border-b border-border pb-6"><Link href={category.href} className="text-xs text-muted-foreground">{category.label}</Link><h1 className="mt-3 font-sans text-[20px] font-bold leading-8">{row.title}</h1><div className="mt-4 text-xs text-muted-foreground">🎊 달밤 · {date}</div></header>
          <div className="mb-6 flex flex-wrap items-center gap-2"><span className="bg-[#b5b9c1] px-1.5 py-1 text-xs text-white">{category.label}</span><h2 className="font-sans text-[20px] font-bold leading-8">{row.title}</h2></div>
          {row.summary?<p className="mb-6 text-sm leading-7 text-muted-foreground">{row.summary}</p>:null}<div className="mb-6 border-t border-border"/>
          {row.image?<figure className="mb-8 overflow-hidden"><img src={row.image} alt={row.title} className="mx-auto h-auto max-h-[680px] w-full object-contain"/></figure>:null}
          <div className="article-content" dangerouslySetInnerHTML={{__html:content(row)}}/>
          <div className="mt-7"><Link href={category.href} className="inline-flex items-center gap-2 text-sm hover:text-accent"><ArrowLeft className="h-4 w-4"/>목록으로</Link></div><ArticleInteractions contentKey={`cms:${row.slug}`}/>
        </article>
        <aside className="min-w-0 space-y-5 self-start"><div className="rounded-2xl bg-card p-3 shadow-[0_10px_30px_rgba(30,26,20,.08)]"><a href="https://t.me/+A3VGGGBdkFllYWE9" target="_blank" rel="noreferrer" className="block aspect-[2268/720] overflow-hidden rounded-t-xl"><img src="/vietdalbam/upload/0e4942bd4a4e4ac699bd991fe4133439.webp" alt="달밤 텔레방" className="h-full w-full object-cover"/></a><a href="https://open.kakao.com/o/gziI3pyh" target="_blank" rel="noreferrer" className="block aspect-[2268/720] overflow-hidden rounded-b-xl"><img src="/vietdalbam/upload/f5d0a13573ff441e95560ae9955acfd7.webp" alt="달밤 단톡방" className="h-full w-full object-cover"/></a></div>
          {recommendations.length?<section className="bg-card p-6 shadow-[0_8px_25px_rgba(30,26,20,.05)]"><p className="text-[10px] tracking-[.25em] text-muted-foreground uppercase">Related posts</p><h2 className="mt-2 font-serif text-2xl">추천 글</h2><div className="mt-5 space-y-5">{recommendations.map(item=>{const image=relatedImage(item.image);return <Link key={`${item.kind}:${item.slug}`} href={relatedHref(item,row.category)} className="group grid grid-cols-[92px_1fr] gap-3 border-b border-border pb-5 last:border-0 last:pb-0"><div className="aspect-[4/3] overflow-hidden bg-secondary">{image?<img src={image} alt="" className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105"/>:null}</div><div><p className="line-clamp-2 text-sm font-medium leading-5 group-hover:text-accent">{item.title}</p><p className="mt-2 text-[10px] text-muted-foreground">{new Date(item.updated_at).toLocaleDateString("ko-KR")}</p></div></Link>})}</div></section>:null}<LiveTravelWidgets/>
        </aside>
      </div>
      <section className="mt-6 w-full min-w-0 max-w-full overflow-hidden">
        {banners?<div className="grid overflow-hidden md:grid-cols-2">{banners.map((banner,index)=><Link key={banner} href={category.href} className="block aspect-[180/57] overflow-hidden"><img src={banner} alt={`${category.label} 배너 ${index+1}`} className="h-full w-full object-cover"/></Link>)}</div>:null}
        <div className="mt-5 rounded-xl bg-card px-7 py-5 shadow-[0_1px_2px_rgba(0,0,0,.04)]"><h2 className="font-sans text-xl font-bold">{category.label}</h2></div>
        <nav className="my-5 flex flex-wrap gap-2.5">{filters.map((filter,index)=><Link key={filter} href={category.href} className={`inline-flex h-10 items-center justify-center rounded-lg px-5 text-sm font-semibold text-white ${index===0?"bg-[#969ba3]":"bg-[#b9bdc5]"}`}>{filter}</Link>)}</nav>
        <div className="grid grid-cols-2 gap-3 sm:gap-5 lg:grid-cols-3">{archiveItems.map(item=>{const image=relatedImage(item.image);return <article key={`archive:${item.kind}:${item.slug}`} className="group overflow-hidden rounded-xl bg-card shadow-[0_1px_2px_rgba(0,0,0,.05)]"><Link href={relatedHref(item,row.category)}><div className="aspect-[4/3] overflow-hidden bg-secondary">{image?<img src={image} alt={item.title} className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105"/>:null}</div><div className="p-4"><h3 className="line-clamp-2 min-h-11 text-sm font-semibold leading-6">{item.title}</h3><div className="mt-3 flex items-center justify-between text-xs text-muted-foreground"><span>🎊 달밤</span><span>{new Date(item.updated_at).toLocaleDateString("ko-KR")}</span></div></div></Link></article>})}</div>
      </section>
    </div></section><Footer/>
  </main>;
}
