"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Eye, ImagePlus, MapPin, Save, Trash2, Upload } from "lucide-react";
import { RichTextEditor } from "@/components/rich-text-editor";

type Article = { id?:number; title:string; slug:string; category:string; summary:string; image:string; body:string; status:string; featured?:boolean; href?:string; mapName:string; mapAddress:string; mapUrl:string; mapEmbedUrl:string; lockedSlug?:boolean };
const taxonomyGroups=[
  {key:"benefits",label:"혜택",items:[["notice","공지사항"],["event","이벤트"],["service","서비스"]]},
  {key:"ho-chi-minh",label:"호치민",items:[["accommodation","숙소 & 풀빌라"],["karaoke","가라오케"],["club","클럽"],["bar","바 & 주점"],["salon","이발소 & 미용실"],["massage","마사지"],["golf","골프"],["sights","여행지"],["restaurant","맛집"]]},
  {key:"da-nang",label:"다낭",items:[["danangroom","숙소 & 풀빌라"],["danangkaraoke","가라오케"],["danangclub","클럽"],["danangbar","바 & 주점"],["danangsalon","이발소 & 미용실"],["danangmassage","마사지"],["danangfood","맛집"]]},
  {key:"nha-trang",label:"나트랑",items:[["nhatrangroom","숙소 & 풀빌라"],["nhatrangktv","가라오케"],["nhatrangclub","클럽"],["nhatrangbar","바 & 주점"],["nhatrangsalon","이발소 & 미용실"],["nhatrangmassage","마사지"],["nhatranggolf","골프"],["nhatrangtravel","여행지"],["nhatrangfood","맛집"]]},
  {key:"da-lat",label:"달랏",items:[["dalatroom","숙소 & 풀빌라"],["dalatktv","가라오케"],["dalatclub","클럽"],["dalatbar","바 & 주점"],["dalatsalon","이발소 & 미용실"],["dalatmassage","마사지"],["dalatgolf","골프"],["dalattravel","여행지"],["dalatfood","맛집"]]},
  {key:"vung-tau",label:"붕따우",items:[["vungtau","숙소 & 풀빌라"],["vungtaukaraoke","가라오케"],["vungtauclub","클럽"],["vungtaubar","바 & 주점"],["vungtausalon","이발소 & 미용실"],["vungtaumassage","마사지"],["vungtaugolf","골프"],["vungtautravel","여행지"],["vungtaufood","맛집"]]},
  {key:"phu-quoc",label:"푸꾸옥",items:[["phuquoc","숙소 & 풀빌라"],["phuquockaraoke","가라오케"],["phuquocclub","클럽"],["phuquocbar","바 & 주점"],["phuquocsalon","이발소 & 미용실"],["phuquocmassage","마사지"],["phuquocgolf","골프"],["phuquoctravel","여행지"],["phuquocfood","맛집"]]},
] as const;
export function AdminContentEditor({article}:{article?:Article}) {
  const router=useRouter();
  const [data,setData]=useState<Article>(article??{title:"",slug:"",category:"",summary:"",image:"",body:"",status:"draft",mapName:"",mapAddress:"",mapUrl:"",mapEmbedUrl:""});
  const [slugEdited,setSlugEdited]=useState(Boolean(article?.slug));
  const [pending,setPending]=useState(false); const [error,setError]=useState("");
  useEffect(()=>{if(article?.id===undefined&&!data.category)setData(current=>({...current,category:"accommodation"}))},[article?.id,data.category]);
  const selectedTaxonomy=taxonomyGroups.find(group=>group.items.some(([value])=>value===data.category))??taxonomyGroups[0];
  const field="mt-2 w-full rounded-md border border-[#8c8f94] bg-white px-3 outline-none focus:border-[#2271b1] focus:ring-1 focus:ring-[#2271b1]";
  const change=(key:keyof Article,value:string|boolean)=>setData(current=>({...current,[key]:value}));
  const makeSlug=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim().replace(/[^a-z0-9가-힣]+/g,"-").replace(/^-|-$/g,"").slice(0,120);
  function changeTitle(value:string){setData(current=>({...current,title:value,slug:article?.lockedSlug||slugEdited?current.slug:makeSlug(value)}))}
  useEffect(()=>{if(!article?.id&&!slugEdited&&data.title&&!data.slug)setData(current=>({...current,slug:makeSlug(current.title)}))},[article?.id,data.slug,data.title,slugEdited]);
  function extractEmbedUrl(value:string){const decoded=value.replace(/&amp;/g,"&").trim();const match=decoded.match(/<iframe[^>]*\ssrc=["']([^"']+)["']/i);return (match?.[1]??decoded).trim()}
  function changeEmbed(value:string){const url=extractEmbedUrl(value);change("mapEmbedUrl",url);if(url.includes("/maps/embed"))setError("")}
  useEffect(()=>{const form=Array.from(document.querySelectorAll("form")).find(item=>item.querySelector(".article-content"));if(!form)return;const paste=(event:ClipboardEvent)=>{const target=event.target;if(!(target instanceof HTMLInputElement)||target.value!==data.mapEmbedUrl)return;const text=event.clipboardData?.getData("text")??"";if(!/<iframe/i.test(text))return;event.preventDefault();changeEmbed(text)};form.addEventListener("paste",paste,true);return()=>form.removeEventListener("paste",paste,true)},[data.mapEmbedUrl]);

  async function upload(file:File|undefined,target:"featured"|"body") {
    if(!file)return; setPending(true); setError(""); const form=new FormData(); form.set("file",file);
    const response=await fetch("/api/admin/media",{method:"POST",body:form}); const result=await response.json() as {url?:string;error?:string}; setPending(false);
    if(!result.url)return setError(result.error??"업로드 실패");
    if(target==="featured")change("image",result.url); else window.dispatchEvent(new CustomEvent("cms-editor-insert-html",{detail:{html:`<figure class="image"><img src="${result.url}" alt="" /></figure><p><br></p>`}}));
  }
  function insertMap(){const url=(data.mapEmbedUrl||data.mapUrl).trim();if(!/^https:\/\/(maps\.app\.goo\.gl\/|(?:www\.)?google\.[^/]+\/maps)/i.test(url))return setError("Google Maps 링크를 입력해주세요.");const isEmbed=/\/maps\/embed/i.test(url)||/[?&]output=embed(?:&|$)/i.test(url);const escape=(value:string)=>value.replace(/[&<>"']/g,(character)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[character]!);const name=escape(data.mapName||"Google Maps");const address=escape(data.mapAddress||"");const safeUrl=escape(url);const html=isEmbed?`<div class="article-map-embed"><p class="article-map-note"><strong>${name}</strong><span>${address}</span></p><div class="article-map-frame"><iframe title="${name} Google Maps" src="${safeUrl}" loading="lazy" allowfullscreen referrerpolicy="no-referrer-when-downgrade"></iframe></div></div><p><br></p>`:`<p><a href="${safeUrl}" target="_blank">📍 ${name}</a></p>`;window.dispatchEvent(new CustomEvent("cms-editor-insert-html",{detail:{html}}));setError("");}
  async function submit(event:FormEvent){event.preventDefault();setPending(true);setError("");const response=await fetch(article?.id?`/api/admin/content/${article.id}`:"/api/admin/content",{method:article?.id?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const result=await response.json() as {error?:string};setPending(false);if(!response.ok)return setError(result.error??"저장 실패");router.push("/admin/content");router.refresh();}
  async function remove(){if(!article?.id||!confirm("이 게시물을 삭제할까요?"))return;setPending(true);const response=await fetch(`/api/admin/content/${article.id}`,{method:"DELETE"});setPending(false);if(!response.ok)return setError("삭제하지 못했습니다.");router.push("/admin/content");router.refresh();}

  return <form onSubmit={submit} className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_320px]">
    <section className="space-y-5 rounded-lg border border-[#c3c4c7] bg-white p-5 shadow-sm md:p-7">
      <label className="block text-sm font-semibold">제목<input required minLength={2} value={data.title} onChange={e=>changeTitle(e.target.value)} className={`${field} h-12 text-lg`}/></label>
      <label className="block text-sm font-semibold">URL 슬러그<div className="mt-2 flex"><span className="flex items-center rounded-l-md border border-r-0 border-[#8c8f94] bg-[#f0f0f1] px-3 text-sm">{data.lockedSlug?"현재 URL":"/article/"}</span><input required readOnly={data.lockedSlug} value={data.slug} onChange={e=>{setSlugEdited(true);change("slug",makeSlug(e.target.value))}} className="h-11 min-w-0 flex-1 rounded-r-md border border-[#8c8f94] px-3 read-only:bg-[#f0f0f1] read-only:text-[#646970]"/></div>{data.lockedSlug?<span className="mt-1 block text-xs font-normal text-[#646970]">DB에서 가져온 게시물은 사용자 페이지 연결을 위해 기존 URL을 유지합니다.</span>:<span className="mt-1 block text-xs font-normal text-[#646970]">제목을 입력하면 URL 슬러그가 자동으로 생성됩니다.</span>}</label>
      <label className="block text-sm font-semibold">요약<textarea value={data.summary} onChange={e=>change("summary",e.target.value)} className={`${field} h-24 py-3`}/></label>
      <div className="rounded-md border border-[#dcdcde] bg-[#f6f7f7] p-4"><p className="flex items-center gap-2 text-sm font-semibold"><MapPin className="size-4"/>Google Maps 현재 정보</p>{data.mapEmbedUrl?<div className="mt-4 overflow-hidden rounded-xl border border-[#d8cbb7] bg-white shadow-sm"><div className="flex flex-wrap items-center gap-x-4 gap-y-1 bg-[#f7f4ef] px-4 py-3"><strong className="text-xs uppercase tracking-[.08em] text-[#8d795c]">{data.mapName||"Google Maps"}</strong><span className="text-sm text-[#646970]">{data.mapAddress}</span></div><div className="p-3"><iframe title={`${data.mapName||"Google Maps"} 미리보기`} src={data.mapEmbedUrl} className="h-[410px] w-full rounded-lg border-0 max-md:h-[300px]" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></div></div>:<div className="mt-3 rounded-md border border-dashed border-[#8c8f94] bg-white p-8 text-center text-sm text-[#646970]">Embed URL을 입력하면 여기에 지도가 표시됩니다.</div>}<div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold">장소명<input value={data.mapName} onChange={e=>change("mapName",e.target.value)} className={`${field} h-10`}/></label><label className="text-xs font-semibold">주소<input value={data.mapAddress} onChange={e=>change("mapAddress",e.target.value)} className={`${field} h-10`}/></label><label className="text-xs font-semibold sm:col-span-2">Google Maps 링크<input type="url" value={data.mapUrl} onChange={e=>change("mapUrl",e.target.value)} className={`${field} h-10`}/></label><label className="text-xs font-semibold sm:col-span-2">Embed URL<input type="url" value={data.mapEmbedUrl} onChange={e=>change("mapEmbedUrl",e.target.value)} className={`${field} h-10`}/></label></div><div className="mt-3 flex flex-wrap gap-2"><button type="button" onMouseDown={()=>window.dispatchEvent(new Event("cms-editor-capture-range"))} onClick={insertMap} className="rounded-md border border-[#2271b1] px-4 py-2 text-sm font-semibold text-[#2271b1]">커서 위치에 지도 삽입</button>{data.mapUrl?<a href={data.mapUrl} target="_blank" rel="noreferrer" className="rounded-md px-4 py-2 text-sm text-[#2271b1] underline">Google Maps에서 열기</a>:null}</div></div>
      <div><p className="mb-2 text-sm font-semibold">본문</p><RichTextEditor value={data.body} onChange={value=>change("body",value)}/></div>
      <label onMouseDown={()=>window.dispatchEvent(new Event("cms-editor-capture-range"))} className="inline-flex cursor-pointer items-center gap-2 rounded-md border border-[#2271b1] px-4 py-2.5 text-sm font-semibold text-[#2271b1]"><ImagePlus className="size-4"/>커서 위치에 본문 이미지 삽입<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" className="hidden" onChange={e=>upload(e.target.files?.[0],"body")}/></label>
    </section>
    <aside className="space-y-5"><section className="rounded-lg border border-[#c3c4c7] bg-white p-5 shadow-sm"><h2 className="font-semibold">게시</h2><label className="mt-4 block text-sm font-semibold">상태<select value={data.status} onChange={e=>change("status",e.target.value)} className={`${field} h-11`}><option value="draft">임시글</option><option value="published">공개</option></select></label><label className="mt-4 block text-sm font-semibold">상위 메뉴 / 지역<select value={selectedTaxonomy.key} onChange={e=>{const group=taxonomyGroups.find(item=>item.key===e.target.value)??taxonomyGroups[0];change("category",group.items[0][0])}} className={`${field} h-11`}>{taxonomyGroups.map(group=><option key={group.key} value={group.key}>{group.label}</option>)}</select></label><label className="mt-4 block text-sm font-semibold">하위 메뉴 / 카테고리<select value={data.category} onChange={e=>change("category",e.target.value)} className={`${field} h-11`}>{selectedTaxonomy.items.map(([value,label])=><option key={value} value={value}>{selectedTaxonomy.label}{label.replaceAll(" ","")}</option>)}</select></label><label className="mt-5 flex cursor-pointer items-start gap-3 rounded-md border border-[#c3c4c7] bg-[#f6f7f7] p-4"><input type="checkbox" checked={Boolean(data.featured)} onChange={e=>change("featured",e.target.checked)} className="mt-0.5 size-5 accent-[#2271b1]"/><span><strong className="block text-sm">추천 게시물</strong><span className="mt-1 block text-xs font-normal text-[#646970]">체크하면 공개 후 랜딩 페이지 추천 영역에 표시됩니다.</span></span></label>{error?<p className="mt-4 rounded-md bg-red-50 p-3 text-sm text-red-700">{error}</p>:null}<button disabled={pending} className="mt-5 flex w-full items-center justify-center gap-2 rounded-md bg-[#2271b1] px-5 py-3 font-semibold text-white disabled:opacity-50"><Save className="size-4"/>{pending?"처리 중...":"저장"}</button>{article?.href&&data.status==="published"?<a href={article.href} target="_blank" className="mt-3 flex items-center justify-center gap-2 rounded-md border border-[#2271b1] px-5 py-2.5 text-sm font-semibold text-[#2271b1]"><Eye className="size-4"/>페이지 보기</a>:null}{article?.id?<button type="button" onClick={remove} className="mt-3 flex w-full items-center justify-center gap-2 rounded-md border border-red-300 px-5 py-2.5 text-sm font-semibold text-red-700"><Trash2 className="size-4"/>삭제</button>:null}</section>
      <section className="rounded-lg border border-[#c3c4c7] bg-white p-5 shadow-sm"><h2 className="font-semibold">대표 이미지</h2>{data.image?<img src={data.image} alt="" className="mt-4 max-h-56 w-full rounded-md object-cover"/>:<div className="mt-4 grid h-40 place-items-center rounded-md bg-[#f0f0f1] text-sm text-[#646970]">이미지 없음</div>}<input value={data.image} onChange={e=>change("image",e.target.value)} className={`${field} h-11 text-xs`}/><label className="mt-3 flex cursor-pointer items-center justify-center gap-2 rounded-md border border-[#2271b1] px-4 py-2.5 text-sm font-semibold text-[#2271b1]"><Upload className="size-4"/>업로드<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" className="hidden" onChange={e=>upload(e.target.files?.[0],"featured")}/></label></section>
    </aside>
  </form>;
}
