"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { KeyRound, Mail } from "lucide-react";

export default function ForgotPasswordPage() {
  const [step, setStep] = useState<"request"|"reset"|"done">("request");
  const [email, setEmail] = useState(""); const [message,setMessage]=useState(""); const [pending,setPending]=useState(false);
  const [code, setCode] = useState("");
  const [newPassword, setNewPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  async function requestOtp(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setMessage(""); const response=await fetch("/api/auth/forgot-password/request",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email})}); const result=await response.json() as {error?:string}; if(response.ok){setStep("reset");setMessage("이메일로 인증번호를 보냈습니다.");}else setMessage(result.error??"발송에 실패했습니다."); setPending(false); }
  async function reset(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if(newPassword!==confirmPassword){setMessage("비밀번호 확인이 일치하지 않습니다.");return;} setPending(true); const response=await fetch("/api/auth/forgot-password/reset",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,code,newPassword})}); const result=await response.json() as {error?:string}; if(response.ok){setStep("done");setMessage("비밀번호가 재설정되었습니다.");}else setMessage(result.error??"재설정에 실패했습니다."); setPending(false); }
  return <main className="grid min-h-screen place-items-center bg-[#f3f1ec] px-5 py-16"><section className="w-full max-w-md rounded-3xl border border-border bg-card p-7 shadow-xl md:p-10"><Link href="/" className="brand-logo font-serif text-xl !text-accent [-webkit-text-stroke:1.25px_#6f6557]">호치민 게임</Link><KeyRound className="mt-10 size-10 text-accent"/><h1 className="mt-4 font-serif text-4xl font-bold">비밀번호 찾기</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">가입한 Gmail로 6자리 인증번호를 보내드립니다.</p>{step==="request"?<form onSubmit={requestOtp} autoComplete="off" className="mt-8 space-y-4"><label className="relative block"><Mail className="absolute left-4 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><input required type="email" name="recoveryEmail" autoComplete="off" value={email} onChange={e=>setEmail(e.target.value)} placeholder="가입한 이메일" className="h-13 w-full rounded-xl border border-input pl-11 pr-4 outline-none focus:border-accent"/></label><button disabled={pending} className="h-13 w-full rounded-xl bg-primary font-bold text-primary-foreground">{pending?"발송 중...":"OTP 인증번호 받기"}</button></form>:step==="reset"?<form onSubmit={reset} autoComplete="off" className="mt-8 space-y-4"><input required name="resetOtp" inputMode="numeric" autoComplete="off" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g, ""))} maxLength={6} placeholder="6자리 OTP" className="h-13 w-full rounded-xl border border-input px-4 text-center text-xl tracking-[.4em] outline-none focus:border-accent"/><input required type="password" name="freshPassword" autoComplete="new-password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} placeholder="새 비밀번호" className="h-13 w-full rounded-xl border border-input px-4 outline-none focus:border-accent"/><input required type="password" name="freshPasswordConfirmation" autoComplete="new-password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} placeholder="새 비밀번호 확인" className="h-13 w-full rounded-xl border border-input px-4 outline-none focus:border-accent"/><button disabled={pending} className="h-13 w-full rounded-xl bg-primary font-bold text-primary-foreground">비밀번호 재설정</button></form>:<Link href="/login" className="mt-8 flex h-13 items-center justify-center rounded-xl bg-primary font-bold text-primary-foreground">새 비밀번호로 로그인</Link>}{message?<p className="mt-4 rounded-lg bg-secondary p-3 text-sm">{message}</p>:null}</section></main>;
}
